"""
Hospital registry for the EVATO emergency-vehicle scenarios.

Holds the real-world hospitals inside the Bangalore map's coverage area,
each with its own colour so a run is instantly identifiable: the hospital's
map marker, and the corridor polyline drawn for that run's route, share one
colour.

Responsibilities:
  1. HOSPITALS - the registry itself (name, lat/lon, colour, short key).
  2. write_hospital_poi_file(...) - generates a SUMO additional-file placing
     every hospital on the map as a colour-coded, named POI. Written once and
     loaded by osm.sumocfg, so hospitals show up in sumo-gui on every run.
  3. resolve_hospital_edge(...) - snaps a hospital's lat/lon to the nearest
     drivable edge, which is what a vehicle can actually be routed to/from
     (a POI marker is only a visual; it is not a routing target).
  4. select_hospital(...) - the per-run choice of which hospital this run is
     about, and whether it is the route's start or its destination.
  5. pick_route_with_hospital(...) - builds the route: the hospital at one
     end, a randomly chosen edge at the other, seeded so a run is repeatable.

The map only covers lon 77.576..77.658 / lat 12.915..12.958, so
MAP_BOUNDS_LONLAT is used to reject any coordinate outside it up front with
a clear message, rather than silently producing an unroutable point.
"""

import random

import traci

# Geographic extent of Bangalore_Map/osm.net.xml.gz (<location origBoundary>).
MAP_BOUNDS_LONLAT = (77.576208, 12.914926, 77.658280, 12.957784)


class Hospital:
    def __init__(self, key, name, lat, lon, color):
        self.key = key
        self.name = name
        self.lat = lat
        self.lon = lon
        self.color = color  # (r, g, b) 0-255

    @property
    def rgba(self):
        return (self.color[0], self.color[1], self.color[2], 255)

    def color_str(self):
        return ",".join(str(c) for c in self.color)

    def in_bounds(self):
        min_lon, min_lat, max_lon, max_lat = MAP_BOUNDS_LONLAT
        return min_lon <= self.lon <= max_lon and min_lat <= self.lat <= max_lat

    def __repr__(self):
        return f"<Hospital {self.key}: {self.name}>"


# Colours are chosen to be mutually distinct AND distinct from the ambulance
# itself (pure red), so a coloured corridor is never confused with the vehicle.
HOSPITALS = [
    Hospital("sagar", "Sagar Hospitals",
             12.92811865612297, 77.59989501982666, (255, 140, 0)),      # orange
    Hospital("kidwai", "Kidwai Memorial Institute of Oncology",
             12.939177153789258, 77.60217083722563, (30, 120, 255)),    # blue
    Hospital("nimhans", "NIMHANS Hospital, Clinical Psychology",
             12.939344456340029, 77.58963955799719, (170, 60, 230)),    # violet
    Hospital("stjohns", "St. John's Medical College Hospital",
             12.930012770629132, 77.6193108688819, (0, 190, 160)),      # teal
]

HOSPITALS_BY_KEY = {h.key: h for h in HOSPITALS}


def get_hospital(key):
    if key not in HOSPITALS_BY_KEY:
        raise KeyError(f"Unknown hospital '{key}'. Known: {', '.join(HOSPITALS_BY_KEY)}")
    return HOSPITALS_BY_KEY[key]


def write_hospital_poi_file(path):
    """Writes the SUMO additional-file that puts every hospital on the map.

    POIs are declared with lon/lat directly (SUMO projects them using the
    network's own projection), each with its registry colour and its full
    name - the name is what sumo-gui draws under the marker once
    poiName_show is enabled in the view settings."""
    out_of_bounds = [h for h in HOSPITALS if not h.in_bounds()]
    if out_of_bounds:
        raise ValueError(
            "These hospitals fall outside the map's coverage area and cannot be "
            "placed: " + ", ".join(h.name for h in out_of_bounds)
        )

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by bangalore/hospitals.py - do not edit by hand. -->",
        '<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">',
    ]
    for h in HOSPITALS:
        lines.append(
            f'    <poi id="hospital_{h.key}" name="{_xml_escape(h.name)}" type="evato.hospital" '
            f'color="{h.color_str()}" layer="30" icon="pin" width="45" height="45" '
            f'lon="{h.lon}" lat="{h.lat}"/>'
        )
    lines.append("</additional>")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def _xml_escape(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;"))


def resolve_hospital_edge(hospital, vclass="passenger"):
    """Snaps a hospital's lat/lon onto the nearest edge a vehicle can use.

    A POI is only a marker - to route an ambulance to or from a hospital we
    need the road that serves it. Requires a live TraCI connection."""
    if not hospital.in_bounds():
        raise ValueError(f"{hospital.name} is outside the map's coverage area.")
    try:
        edge_id, _pos, _lane_idx = traci.simulation.convertRoad(
            hospital.lon, hospital.lat, isGeo=True, vClass=vclass)
    except traci.TraCIException as e:
        raise RuntimeError(f"Could not snap {hospital.name} to a road: {e}")
    if not edge_id or edge_id.startswith(":"):
        raise RuntimeError(f"{hospital.name} snapped to an invalid edge ({edge_id!r}).")
    return edge_id


def select_hospital(hospital_key=None, role=None, rng=None):
    """Resolves which hospital this run is about and whether it sits at the
    route's start or its destination.

    Passing both explicitly (from CLI flags) keeps automated/background runs
    non-interactive; leaving them out prompts the user to choose, which is
    the intended flow for an interactive run."""
    rng = rng or random
    if hospital_key:
        hospital = get_hospital(hospital_key)
    else:
        hospital = _prompt_for_hospital()
    if role not in ("start", "destination"):
        role = _prompt_for_role() if role is None else role
    if role == "random":
        role = rng.choice(["start", "destination"])
    return hospital, role


def _prompt_for_hospital():
    print("\nSelect the hospital for this run:")
    for idx, h in enumerate(HOSPITALS, start=1):
        print(f"  {idx}. {h.name}  [{h.key}]")
    while True:
        raw = input(f"Enter 1-{len(HOSPITALS)} (or the key): ").strip()
        if raw in HOSPITALS_BY_KEY:
            return HOSPITALS_BY_KEY[raw]
        if raw.isdigit() and 1 <= int(raw) <= len(HOSPITALS):
            return HOSPITALS[int(raw) - 1]
        print("  Not a valid choice, try again.")


def _prompt_for_role():
    print("\nShould the hospital be the route's START or its DESTINATION?")
    print("  1. destination  (ambulance drives TO the hospital - the usual emergency case)")
    print("  2. start        (ambulance departs FROM the hospital)")
    while True:
        raw = input("Enter 1-2 (or start/destination): ").strip().lower()
        if raw in ("start", "destination"):
            return raw
        if raw == "1":
            return "destination"
        if raw == "2":
            return "start"
        print("  Not a valid choice, try again.")


def pick_route_with_hospital(hospital, role, seed=42, min_edges=12, max_edges=45,
                              attempts=400, vclass="passenger", edge_to_tl=None,
                              min_signals=3, max_evaluations=60):
    """Builds this run's route with the hospital pinned at one end and the
    other end chosen at random.

    `seed` makes that random choice repeatable, so the same command produces
    the same route every time - the two scenarios of a run (with and without
    the green corridor) must drive an identical route for their comparison
    to mean anything, and a rerun should be reproducible for research use.

    When `edge_to_tl` is supplied, candidate routes are scored by how many
    distinct signalised junctions they pass through, and the richest is
    chosen. This matters: an emergency-preemption system can only act at
    traffic lights, so a route that happens to pass none makes the EVP and
    baseline scenarios byte-identical and the comparison meaningless. Length
    alone does not guarantee signals, so it is scored for explicitly.

    Returns (from_edge, to_edge, route_edges, other_edge)."""
    rng = random.Random(seed)
    hospital_edge = resolve_hospital_edge(hospital, vclass=vclass)

    candidates = [e for e in traci.edge.getIDList() if not e.startswith(":")]
    if not candidates:
        raise RuntimeError("No usable edges found in the network.")
    rng.shuffle(candidates)

    def count_signals(route_edges):
        if not edge_to_tl:
            return None
        return len({edge_to_tl[e] for e in route_edges if e in edge_to_tl})

    def allows_vclass(edge_id):
        """Skip edges the vehicle could never depart from (footpaths, rail,
        service ways). Without this, findRoute is called on them anyway and
        SUMO logs a server-side error for each - hundreds of lines of noise
        in any captured run log, for attempts that were never viable."""
        try:
            allowed = traci.lane.getAllowed(f"{edge_id}_0")
        except traci.TraCIException:
            return False
        # An empty allow-list means "all vehicle classes permitted".
        return not allowed or vclass in allowed

    best_in_window = None   # (n_signals, from, to, edges, other)
    best_any = None         # fallback if nothing lands inside the length window
    evaluated = 0

    for other_edge in candidates[:attempts]:
        if other_edge == hospital_edge or not allows_vclass(other_edge):
            continue
        from_edge, to_edge = (
            (hospital_edge, other_edge) if role == "start" else (other_edge, hospital_edge)
        )
        try:
            route = traci.simulation.findRoute(from_edge, to_edge, vType="")
        except traci.TraCIException:
            continue
        route_edges = list(route.edges)
        if len(route_edges) < 2:
            continue

        candidate = (from_edge, to_edge, route_edges, other_edge)
        if min_edges <= len(route_edges) <= max_edges:
            n_signals = count_signals(route_edges)
            if edge_to_tl is None:
                return candidate
            evaluated += 1
            if best_in_window is None or n_signals > best_in_window[0]:
                best_in_window = (n_signals,) + candidate
            # Good enough - stop early rather than scanning every candidate.
            if n_signals >= min_signals or evaluated >= max_evaluations:
                break
        elif best_any is None or abs(len(route_edges) - min_edges) < abs(len(best_any[2]) - min_edges):
            best_any = candidate

    if best_in_window is not None:
        n_signals, from_edge, to_edge, route_edges, other_edge = best_in_window
        if n_signals is not None and n_signals < min_signals:
            print(f"[hospitals] Warning: best route found passes only {n_signals} "
                  f"signalised junction(s) (wanted >= {min_signals}). The green corridor "
                  f"has little to act on, so the EVP-vs-baseline comparison will be weak; "
                  f"try a different --seed or hospital.")
        return from_edge, to_edge, route_edges, other_edge

    if best_any is not None:
        print(f"[hospitals] No route within {min_edges}-{max_edges} edges; "
              f"using closest match ({len(best_any[2])} edges).")
        return best_any
    raise RuntimeError(
        f"Could not build any route with {hospital.name} as the {role} "
        f"after {attempts} attempts."
    )


def build_route_shape(route_edges):
    """Concatenates each edge's lane-0 shape into one continuous polyline in
    network coordinates, for drawing the route as a GUI polygon."""
    shape = []
    for edge_id in route_edges:
        try:
            pts = traci.lane.getShape(f"{edge_id}_0")
        except traci.TraCIException:
            continue
        if shape and pts and shape[-1] == pts[0]:
            shape.extend(pts[1:])
        else:
            shape.extend(pts)
    return shape


def draw_route_corridor(route_edges, hospital, role, poly_id="ambulance_corridor"):
    """Draws the run's route in the hospital's own colour, with markers at
    both ends - so the corridor on screen is visually tied to the hospital
    pin it serves. The hospital end is drawn in the hospital colour; the
    other end is drawn dark, so direction of travel is readable at a glance."""
    shape = build_route_shape(route_edges)
    if not shape:
        return False
    try:
        traci.polygon.add(poly_id, shape, hospital.rgba, fill=False, layer=20, lineWidth=4)
        start_xy, end_xy = shape[0], shape[-1]
        hospital_xy, other_xy = (
            (start_xy, end_xy) if role == "start" else (end_xy, start_xy)
        )
        traci.poi.add(f"{poly_id}_hospital_end", hospital_xy[0], hospital_xy[1],
                       hospital.rgba, poiType="evato.route_hospital_end",
                       layer=25, width=28, height=28)
        traci.poi.add(f"{poly_id}_other_end", other_xy[0], other_xy[1],
                       (30, 30, 30, 255), poiType="evato.route_other_end",
                       layer=25, width=22, height=22)
        return True
    except traci.TraCIException as e:
        print(f"[hospitals] Could not draw route corridor: {e}")
        return False


if __name__ == "__main__":
    # Regenerate the POI additional-file: python hospitals.py
    from pathlib import Path
    target = Path(__file__).resolve().parent.parent / "Bangalore_Map" / "hospitals.add.xml"
    write_hospital_poi_file(target)
    print(f"Wrote {target}")
    for h in HOSPITALS:
        print(f"  {h.color_str():>15}  {h.name}")
